version: '2.3'

services:

  web:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/web/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - $LISTEN:80

  app:
    build:
      context: docker/app
      args:
        NOMEROFF_NET_REV: bcb4bcc
    command: waitress-serve --call 'main:create_app'
    working_dir: /var/www/app
    restart: unless-stopped
    # uncomment `runtime` to use GPU
    # runtime: nvidia
    scale: 1
    volumes:
      - ./:/var/www/app
      - ./models:/var/www/nomeroff-net/data/models
    environment:
      - TF_FORCE_GPU_ALLOW_GROWTH=true
    logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "5"